name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build

      - name: Write .env file for Cloud Functions
        run: |
          echo "API_TOKEN=#
          ${{ secrets.RAPIDAPI_KEY }}" > functions/.env

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLIGHT_TO_CALENDAR_762FA }}
          projectId: flight-to-calendar-762fa
          channelId: live
